config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  devise_for :users
  resources :users
  resources :posts
  get :user_posts, to: "posts#user_posts"
  resources :tags, only: [:index, :show]
  match "/posts/add_new_comment" => "posts#add_new_comment", as: "add_new_comment_to_posts", via: [:post]
  get :delete_comment, controller: 'posts', action: 'delete_comment'
 end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, polymorphic: true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user

  def is_new?
    created_at > 15.minute.ago
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  acts_as_commentable
  acts_as_taggable_on :tags
  paginates_per 5
  scope :ordered, proc{ order(:created_at) }
  scope :approved, ->{where(approved: true)}
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, if: :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:create, :edit, :update, :destroy, :new, :user_posts]
  def index
    @posts = Post.ordered.approved.page params[:page]
    @all_tags = ActsAsTaggableOn::Tag.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  def add_new_comment
    post = Post.find(params[:id])
    post.comments << current_user.comments.create!(params.require(:comment).permit!)
    redirect_to action: :show, id: post, notice: 'Comment was successfully created.'
  end

  def delete_comment
    comment = current_user.comments.find(params[:comment_id])
    post = Post.find(params[:post_id])
    if comment.is_new?
      comment.destroy
      redirect_to action: :show, id: post, notice: 'Comment was successfully destroyed.'
    else
      redirect_to action: :show, id: post, notice: 'Comment was not destroyed.'
    end
  end

  def user_posts
    @posts = current_user.posts.ordered
  end

  private

    def set_post
      @post = current_user.posts.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:user_id, :title, :body, :approved, :tag_list)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.all
  end

  def show
    @tag =  ActsAsTaggableOn::Tag.find(params[:id])
    @posts = Post.tagged_with(@tag.name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, except: :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, alert: "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, notice: "User updated."
    else
      redirect_to users_path, alert: "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, notice: "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, alert: "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/acts_as_taggable_on/tags/_tag.html.slim
= link_to tag.name, tag_path(tag)

app/views/layouts/_footer.html.erb
<hr>

<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <ul class="list-inline text-center">
                    <li>
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; Your Website 2014</p>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header class="intro-header" style="background-image: url('/home-bg.jpg')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>Clean Blog</h1>
                    <hr class="small">
                    <span class="subheading">A Clean Blog Theme by Start Bootstrap</span>
                </div>
            </div>
        </div>
    </div>
</header>

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to 'Start Bootstrap', root_path, class: 'navbar-brand' %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <%= render 'layouts/navigation_links' %>
                <%= render 'layouts/nav_links_for_auth' %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li>
    <%= link_to 'Home', root_path %>
</li>
<li>
    <%= link_to 'About', page_path('about') %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "My Application" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "My Application" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- Custom Fonts -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <%= render 'layouts/header' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.slim
.container
  .row
    .slider-container
      #slider
        = image_tag("/slider/1.jpg", alt: "Slide 1", class: "sl", style: "display: block;")
        = image_tag("/slider/2.jpg", alt: "Slide 2", class: "sl", style: "display: none;")
        = image_tag("/slider/3.jpg", alt: "Slide 3", class: "sl", style: "display: none;")
        .caption
          .row
            .col-sm-2
              .point
                a href="#" id="prev" <<
                a href="#" id="next" >>
            .col-sm-5
              .text-block
                | Фотографиям вашего ребенка позавидуют даже звезды
            .col-sm-5
              .button-block
                a href="#" НАЧАТЬ ОБУЧЕНИЕ >>

app/views/posts/_form.html.slim
= simple_form_for(@post) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :body
    = f.input :tag_list
    = f.input :approved

  .form-actions
    = f.button :submit

app/views/posts/_post.html.slim
h2= link_to post.title, post_path(post)

app/views/posts/edit.html.slim
h1 Editing post

== render 'form'

= link_to 'Show', @post
'|
= link_to 'Back', posts_path

app/views/posts/index.html.slim
.container
  .row
    .tagcloud
      - @all_tags.each do |tag|
        ul style="display:inline-block;"
          li= link_to tag_path(tag) do
            span= tag.name
    .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
      - @posts.each do |post|
        .post-preview
          = link_to post_path(post) do
            h2.post-title= post.title
            p.post-meta= post.user.name
            h5 Tags
            .tags
              = render post.tags
            hr
    = paginate @posts, theme: 'twitter-bootstrap-3'
    ul.pager
      - if current_user 
        li
          = link_to 'New Post', new_post_path
        li
          = link_to 'My Posts', user_posts_path

app/views/posts/new.html.slim
.container
  .row
    .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
      h1 New post
      == render 'form'
      = link_to 'Back', posts_path

app/views/posts/show.html.slim
p#notice = notice
article
  .container
    .row
      .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
        h2= @post.title
        p= @post.body
        h4 Tags
        .tags
          = render @post.tags
        hr
        = form_tag "/posts/add_new_comment" do
          = hidden_field_tag "id", @post.id
          = text_area_tag "comment[comment]", nil, class: "form-control"
          br
          = submit_tag "Post Comment", class: "btn btn-default"
        hr
        - if @post.comments.count > 0
          - @post.comments.each do |comment|
            .row.comment_block
              .col-sm-2
                .thumbnail
                  img.img-responsive.user-photo src="/avatar.png"
              .col-sm-10
                .panel.panel-default
                  .panel-heading
                    strong= comment.user.name
                    span.text-muted= comment.created_at.strftime('%b %e, %l:%M %p')
                .panel-body= comment.comment
                - if current_user == comment.user && comment.is_new?
                  = link_to 'Delete', delete_comment_path(comment_id: comment.id, post_id: @post.id)
        - else
          h4 There is no comments yet.
ul.pager
  - if current_user == @post.user
    li
      = link_to 'Edit', edit_post_path(@post)
  li
    = link_to 'Back', posts_path

app/views/posts/user_posts.html.slim
.container
  .row
    .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
      - @posts.each do |post|
        .post-preview
          = link_to post_path(post) do
            h2.post-title= post.title
            hr

app/views/tags/index.html.slim
.container
  .row
    .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
      h3 Tags
      = render @tags

app/views/tags/show.html.slim
.container
  .row
    .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
      h3= @tag.name
      div= render @posts

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>